# Generated by Django 4.2.5 on 2023-09-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ip',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
